import { useEffect, useState, type ReactNode } from "react";
import { ensureSupabaseReady } from "@/lib/supabase";

const CONFIG_BOUNDARY_VERSION = "runtime-config-v2";

type State =
  | { status: "loading" }
    | { status: "ready" }
      | { status: "error"; message: string };

      export function ConfigBoundary({ children }: { children: ReactNode }) {
        const [state, setState] = useState<State>({ status: "loading" });

          useEffect(() => {
              let cancelled = false;
                  ensureSupabaseReady()
                        .then(() => {
                                if (!cancelled) setState({ status: "ready" });
                                      })
                                            .catch((e: unknown) => {
                                                    if (cancelled) return;
                                                            const message = e instanceof Error ? e.message : String(e);
                                                                    setState({ status: "error", message });
                                                                          });
                                                                              return () => {
                                                                                    cancelled = true;
                                                                                        };
                                                                                          }, []);

                                                                                            if (state.status === "loading") {
                                                                                                return (
                                                                                                      <div data-config-version={CONFIG_BOUNDARY_VERSION}
                                                                                                              style={{
                                                                                                                        minHeight: "100vh",
                                                                                                                                  display: "grid",
                                                                                                                                            placeItems: "center",
                                                                                                                                                      fontFamily: "system-ui, sans-serif",
                                                                                                                                                                color: "#444",
                                                                                                                                                                        }}
                                                                                                                                                                              >
                                                                                                                                                                                      Loading…
                                                                                                                                                                                            </div>
                                                                                                                                                                                                );
                                                                                                                                                                                                  }

                                                                                                                                                                                                    if (state.status === "error") {
                                                                                                                                                                                                        return (
                                                                                                                                                                                                              <div
                                                                                                                                                                                                                      role="alert"
                                                                                                                                                                                                                              style={{
                                                                                                                                                                                                                                        minHeight: "100vh",
                                                                                                                                                                                                                                                  display: "grid",
                                                                                                                                                                                                                                                            placeItems: "center",
                                                                                                                                                                                                                                                                      padding: "2rem",
                                                                                                                                                                                                                                                                                fontFamily: "system-ui, sans-serif",
                                                                                                                                                                                                                                                                                          background: "#fff8f7",
                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                <div style={{ maxWidth: 560, textAlign: "left" }}>
                                                                                                                                                                                                                                                                                                                          <h1 style={{ fontSize: "1.4rem", margin: 0, color: "#7a1d1d" }}>
                                                                                                                                                                                                                                                                                                                                      PractiVault is misconfigured
                                                                                                                                                                                                                                                                                                                                                </h1>
                                                                                                                                                                                                                                                                                                                                                          <p style={{ marginTop: 12, color: "#333" }}>
                                                                                                                                                                                                                                                                                                                                                                      The frontend could not load runtime configuration. This usually
                                                                                                                                                                                                                                                                                                                                                                                  means the server is missing <code>SUPABASE_URL</code> and{" "}
                                                                                                                                                                                                                                                                                                                                                                                              <code>SUPABASE_ANON_KEY</code> environment variables.
                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ marginTop: 12, color: "#555", fontSize: "0.9rem" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                              Details: <code>{state.message}</code>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ marginTop: 12, color: "#555", fontSize: "0.9rem" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Set the variables on Railway and redeploy. No client-side change is
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return <>{children}</>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
